# Generated by Django 4.2.30 on 2026-06-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_text', models.CharField(default='D.', help_text="Short text shown as the navbar logo (e.g. 'D.').", max_length=20)),
                ('logo_image', models.ImageField(blank=True, help_text='Optional logo image. If set, it replaces the logo text in the navbar.', null=True, upload_to='site/')),
                ('hero_highlight_color', models.CharField(default='#b8d4f0', help_text='CSS colour value for the blue highlight behind the hero name/bio (e.g. #b8d4f0).', max_length=20)),
                ('hero_eyebrow', models.CharField(default='est. 2003 · kathmandu', help_text='Small text above the hero name.', max_length=100)),
                ('hero_name', models.CharField(default='Handsome Dikshyant.', help_text='Main hero heading (your name).', max_length=100)),
                ('hero_bio', models.TextField(default="Builder of things. Collector of moments.\nThis isn't a portfolio — it's my life, written down.", help_text='Short bio shown below the name. Use a newline for a line break.')),
                ('hero_handle', models.CharField(default='@dikashyanta', help_text='Social handle shown below the bio.', max_length=60)),
                ('hero_photo', models.ImageField(blank=True, help_text='Profile photo shown on the right side of the hero section.', null=True, upload_to='site/')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
