# Generated by Django 4.2.30 on 2026-07-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='intro_text',
            field=models.TextField(default='Not a resume. Not a portfolio.\nJust a person trying to build things,\nsee places, and remember it all.'),
        ),
    ]
